version: '2'

services:

  node:
    image: appjs
    build: .
    ports:
      - "8080:3000"
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
